name: fanatic 
on:
  schedule:
  - cron: '7 13 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Execute Python script
        uses: nick-invision/retry@v2.4.0
        env:
          SO_USERNAME: ${{ secrets.SO_USERNAME }}
          SO_PASSWORD: ${{ secrets.SO_PASSWORD }}
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          retry_on: error
          command: |
            python fanatic.py
      - name: Keep Alive
        uses: gautamkrishnar/keepalive-workflow@master
